pipeline {
    agent any
    
    stages {
        stage('docker build') {
            steps {
                // Checkout the code from your version control system (e.g., Git)
                git branch: 'dev', url: 'https://github.com/priyaa1255/lms-team-1.git'
            }
        }
        
      
