pipeline {
    agent any 
    stages {
        stage('container remove') {
            steps {
                sh 'docker container rm -f be'
            }
        }
        stage('Build') {
            steps {
                sh 'cd LMS-BE && docker build -t backend .'
            }
        }
        stage('run') {
            steps {
                sh 'docker run -dt --name lmsbe -p 8080:8080 backend'
            }
        }
    }
}
