pipeline {
    agent any
   stages {
       stage('Docker db') {
            steps {
                sh 'sudo docker container run -dt --name lmsdb1 -e MYSQL_ROOT_PASSWORD=Qwerty@123 -p 3309:3306 mysql:latest'
            }
        }
       stage('Docker Build') {
            steps {
                sh 'cd LMS-BE && docker build -t backend .'
            }
        }
        stage('container remove') {
            steps {
                sh 'sudo docker container rm -f be'
            }
        }
        stage('Docker container') {
            steps {
                sh 'sudo docker container run -dt --name be -p 9090:8080 backend'
            }
        }
    }
}

















