pipeline {
    agent any
    stages {
        stage ('Docker Build') {
            steps {
                sh 'cd lms-fe/lmsv1 && docker build -t frontend .'
            }
        }
        stage ('container') {
            steps {
                sh 'docker container run -dt --name fe -p 80:80 backend'
            }
        }
    }
}
