pipeline {
    agent any
    stages {
        stage ('Checkout') {
            steps {
                sh 'echo checkout SCM'
            }
        }
        stage ('remove container') {
            steps {
                sh 'docker container rm -f fe'
            }
        }
        stage ('Docker Build') {
            steps {
                sh 'cd lms-fe/lmsv1 && docker build -t frontend .'
            }
         }
        stage ('docker run') {
            steps {
                sh 'docker container run -dt --name fe -p 80:80 frontend'
            }
        }
    }
}
